### ISSUE TITLE
软件设置

### ISSUE THREAD

**Issue by sunnyday2006** [miaomiaosoft/DnsForwarderGUI#5]
你好。关于两个软件设置，有点疑问：

1、dnsforwarder的安装
1 下载可执行文件
2 下载配置文件。将配置文件和可执行文件放到一个文件夹中并把配置文件重命名为 dnsforwarder.config。
3 对配置文件进行适当的修改，如果不知道如何修改，则跳过此步。
4 运行 dnsforwarder.exe
5 修改系统 DNS 为 127.0.0.1

第3步怎么进行“适当的修改”，想了解一下。像这样修改本机DNS，大概能做哪些额外的事？
第4步运行时，出现长驻的命令行窗口，显示如下内容
Jul 04 18:21:40 [INFO] New session.
Jul 04 18:21:40 [INFO] UDP interface 127.0.0.1:53 opened.
Jul 04 18:21:40 [INFO] Disabled domains initialized.
Jul 04 18:21:40 [INFO] Disabled types initialized.
Jul 04 18:21:40 [INFO] Disabled list initialized.
Jul 04 18:21:40 [INFO] Server groups initialized.

这个窗口保留还是可以直接关掉？
进行完第4步，如何修改系统DNS为127.0.0.1？

2、GUI的安装
内置DnsChooser，默认绑定：127.0.0.3:56，当然你也可以自行改为其它地址
安装DnsChooser服务后需要将DnsForwarder配置文件中的“UDPGroup”改为“UDPGroup 127.0.0.3:56 * on”

我已经把DnsForwarderGUI所有文件放到DnsForwarder目录内，搜索dnsforwarder配置文件，是修改以下这一段的“UDPGroup” 为 “UDPGroup 127.0.0.3:56 * on” 吗？

“<td id="LC65" class="blob-code blob-code-inner js-file-line"># UDPGroup &lt;IP1[:PORT],IP2[:PORT],...&gt; &lt;DOMAIN1,DOMAIN2,...&gt; &lt;on|off&gt;”

3.关于dns污染的问题
我在V2ex上看到原dnschooser作者帖子下有留言关于dns染污的问题
https://www.v2ex.com/t/419555#r_5697517

问一下dnsforwarder会存在这个可能吗？装完了gui是以dnschooser为主，还是dnsforwarder为主？

**Comment by miaomiaosoft** [comment]
适当修改就是看配置文件注释看着改就是了
长驻的命令行窗口关掉就退出了，也正是因为这个我才弄个GUI，换用GUI启动服务后可以把命令行窗口隐藏掉
修改系统DNS这个可以百度了解

dnsforwarder我主要用来分流解析，dnschooser的配置都用的国外非标准端口解析，不存在污染问题
国内网站走dnsforwarder内设定的白名单域名
其他不在白名单外的网站全走dnschooser

装完了gui是以dnsforwarder为主

我建议你把dnsforwarder的中文注释都看明白了就懂怎么用了，帖一份我的配置中一部分给你参考：
`# LogOn <BOOLEAN>
# 是否打开文件日志输出 (since 5.0.4)
LogOn true

# LogFileThresholdLength <NUM>
# 单个日志文件大小的临界值（字节）(since 5.0.4)
# 当日志文件大小超过这个临界值后，当前的日志文件将会被重命名，然后建立一个新的日志文件，继续记录日志
LogFileThresholdLength 102400

# LogFileFolder <PATH>
# 设定日志文件所在的文件夹 (since 5.0.4)
# 日志文件初始的文件名为 `dnsforwarder.log'，当超过临界值之后，将会被重命名为 `dnsforwarder.log.1'、`dnsforwarder.log.2' 等等，然后重新建立一个 dnsforwarder.log' 文件
# 此路径的默认值为程序所在的文件夹（Windows）或程序的配置文件夹（Linux）
LogFileFolder Z:\WINRAR

##################################################
#
# 本地
#
##################################################

# UDPLocal <IP[:PORT]>,<IP[:PORT]>,...
# 设置在本地开启的接口的IP地址和端口，可以是本地回环地址 (127.0.0.1) ，本地局域网，以及互联网 (since 6.0.0)
# 如果是 IPv6 地址，请在IP两端加上方括号（不包含端口部分），例如 [::1]:53 (本地回环)、[fe80::699c:f79a:9bb6:1]:5353 (since 6.0.0)
# 可以设置多个地址，用半角逗号（`,'）分割
# 如果不指定端口，则默认为 53
#
# 示例：
# UDPLocal 127.0.0.1:53,[::1]:53
UDPLocal 127.0.0.1:53,[::1]:53

# 这一版本暂时不支持在本地开启 TCP 端口，以后会加上

##################################################
#
# IP 选择策略
#
##################################################

#########################
# 服务器地址
#########################

# UDPGroup <IP1[:PORT],IP2[:PORT],...> <DOMAIN1,DOMAIN2,...> <on|off>
# 设置一个 UDP 上游服务器组，并指定通过这些上游服务器查询的域名 (since 6.0.0)
# 第一部分参数“<IP1[:PORT],IP2[:PORT],...>”，用于指定 UDP 上游服务器，不写端口则默认使用 53 端口
# 第二部分参数“<DOMAIN1,DOMAIN2,...>”，用于指定通过这些 UDP 上游服务器查询的域名，可以包含通配符
# 第三部分参数“<on|off>”，用于指定是否开启并发查询，`on' 为开启，`off' 为不开启
# 并发查询指的是，向所有指定的 UDP 服务器发送查询请求，取最先接受到的未屏蔽的回复作为查询结果，并丢弃其余的回复
# 可以有多条 `UDPGroup' 选项
#UDPGroup 114.114.114.114:53,223.5.5.5:53 * on
#UDPGroup 101.6.6.6:53,223.113.97.99:53,208.67.222.222:5353,202.141.162.123:53,202.38.93.153:53,202.141.178.13:53,8.26.56.26:443,130.255.78.223:5353,107.181.168.52:5300 * on
UDPGroup 127.0.0.3:56 * on

# TCPGroup <IP1[:PORT],IP2[:PORT],...> <DOMAIN1,DOMAIN2,...> <no|PROXY1[:PORT],PROXY2[:PORT],...>
# 设置一个 TCP 上游服务器组，并指定通过这些上游服务器查询的域名 (since 6.0.0)
# 第一部分参数“<IP1[:PORT],IP2[:PORT],...>”，用于指定 TCP 上游服务器，不写端口则默认使用 53 端口
# 第二部分参数“<DOMAIN1,DOMAIN2,...>”，用于指定通过这些 TCP 上游服务器查询的域名，可以包含通配符
# 第三部分参数“<no|PROXY1[:PORT],PROXY2[:PORT],...>”，用于指定查询时使用的 Socks5 代理，不写端口则默认使用 1080 端口。`no' 代表不使用代理
# 可以有多条 `TCPGroup' 选项
#
# 示例一：
#  TCPGroup 1.2.4.8:53,114.114.114.114 *.example.com 192.168.50.5:8080,192.168.50.6:8080
# `*.example.com' 将通过 192.168.50.5:8080 或 192.168.50.6:8080 两个 Socks5 代理，使用 TCP 协议向 1.2.4.8:53 或 114.114.114.114 进行查询
# 示例二：
#  TCPGroup 8.8.8.8,114.114.114.114:53 * no
# `*.example.com' 将使用 TCP 协议直接向 8.8.8.8 或 114.114.114.114:53 进行查询，不使用代理
#TCPGroup 203.80.96.10,202.14.67.4,202.175.113.124,168.95.1.1,210.220.16.245,101.110.0.26 * 127.0.0.1:9798

# GroupFile <PATH>
# 从文件加载服务器组 (since 6.1.3)
# 服务器组文件的写法请参阅：https://github.com/holmium/dnsforwarder/wiki/GroupFile-%E7%9A%84%E5%86%99%E6%B3%95-%7C-How-to-write-GroupFiles
# 可以有多条 `GroupFile' 选项
#
# 示例一：
#  GroupFile D:\group.txt
#
# 示例二：
#  GroupFile /etc/group.txt
#GroupFile %PROGRAMDIRECTORY%\GroupFileTemp.txt
#GroupFile %PROGRAMDIRECTORY%\UDPGroupFile.txt
#GroupFile %PROGRAMDIRECTORY%\TCPGroupFile.txt
GroupFile %PROGRAMDIRECTORY%\GroupFileIPv6.txt
#GroupFile %PROGRAMDIRECTORY%\GroupFileBlack.txt
GroupFile %PROGRAMDIRECTORY%\GroupFileWhite.txt`
